bedroom_choices={
'1':1,
'2':2,
'3':3,
'4':4,
'5':5,
'6':6,
'7':7,
'8':8,
'9':9,
'10':10
}


price_choices={
    '100000':'$10,0000',
     '200000':'$20,0000',
    '300000':'$30,0000',
    '400000':'$40,0000',
    '500000':'$50,0000',
    '600000':'$60,0000',
    '700000':'$70,0000',
    '800000':'$80,0000',

}

state_choices={
                    "AL" :'Alabama', 
                    "AK" :'Alaska', 
                    "AZ" :'Arizona',
                    "AR" :'Arkansas',
                    "CA" :'California',
                    "CO" :'Colorado', 
                    "CT" :'Connecticut',
                    "DE" :'Delaware',
                    "DC" :'District Of Columbia',
                    "FL" :'Florida',
                    "GA" :'Georgia',
                    "HI" :'Hawaii',
                    "ID" :'Idaho',
                    "IL" :'Illinois',
                    "IN" :'Indiana',
                    "IA" :'Iowa',
                    "KS" :'Kansas',
                    "KY" :'Kentucky',
                    "LA" :'Louisiana',
                    "ME" :'Maine',
                    "MD" :'Maryland',
                    "MA" :'Massachusetts', 
                    "MI" :'Michigan',
                    "MN" :'Minnesota',
                    "MS" :'Mississippi', 
                    "MO" :'Missouri',
                    "MT" :'Montana',
                    "NE" :'Nebraska',
                    "NV" :'Nevada',
                    "NH" :'New Hampshire', 
                    "NJ" :'New Jersey',
                    "NM" :'New Mexico',
                    "NY" :'New York',
                    "NC" :'North Carolina', 
                    "ND" :'North Dakota',
                    "OH" :'Ohio',
                    "OK" :'Oklahoma', 
                    "OR" :'Oregon',
                    "PA" :'Pennsylvania',
                    "RI" :'Rhode Island', 
                    "SC" :'South Carolina',
                    "SD" :'South Dakota',
                    "TN" :'Tennessee',
                    "TX" :'Texas',
                    "UT" :'Utah',
                    "VT" :'Vermont', 
                    "VA" :'Virginia',
                    "WA" :'Washington', 
                    "WV" :'West Virginia', 
                    "WI" :'Wisconsin', 
                    "WY" :'Wyoming', 
   }
#print(bedroom_choices)
#print(prices_choices)
#print(state_choices)